[build]
  # Comando de construcción para Next.js
  command = "npm run build"
  # Directorio de salida para producción
  publish = "out"
  
[build.environment]
  # Variables de entorno para construcción
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "production"
  
# Configuración para redirigir todas las rutas al index.html (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Headers para seguridad y rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache para assets estáticos
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"